version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wifes-next-tip-of-the-week"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ivrh65lxfocw"
s3_prefix = "wifes-next-tip-of-the-week"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
